### ISSUE TITLE
Лаб 9

### ISSUE THREAD

**Issue by mackoel** [Fekloduv/Lab9#1]
Несколько замечаний:
- пришлось по рыскать, чтобы понять кто автор, стоит подписываь отчеты,
- не стоило сливать в один файл,
- Ваш код плохо отработает при не правильном уазании размера буфера в конфиге и при большом объеме входных данных.

**Comment by Fekloduv** [comment]
Константин Николаевич здравствуйте, исправил недочёты

**Comment by mackoel** [comment]
Не все учли

**Comment by Fekloduv** [comment]
Сделал под каждый класс отдельный файл

**Comment by mackoel** [comment]
Это хорошо, но вот Ваш код плохо отработает при не правильном указании размера буфера в конфиге, например, напишите там "десять" словом, и при большом объеме входных данных, т.к. Вы их аккумулируете в памяти.

**Comment by Fekloduv** [comment]
Добавил ограничение на указание размера буфера. Теперь данные хранятся во временном файле

**Comment by mackoel** [comment]
Анатолий, да, так лучше. Зачел
